config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :articles 
  root "pages#home"
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories,except: [:destroy]
end

app/models/article.rb
class Article <ApplicationRecord

  belongs_to :user
  
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum:6, maximum:100}
  validates :description, presence: true,length:{minimum:10, maximum:300}
end    

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

      before_action :set_article, only: [:show, :edit, :update, :destroy] 
      before_action :require_user, except: [:show, :index] 
      before_action :require_same_user, only: [:edit, :update, :destroy]

      def show
            #@article=Article.find(params[:id])
      end    

      def index
        #@articles=Article.all
        @articles= Article.paginate(page: params[:page], per_page: 5)
      end    

      def new 
        @article=Article.new
      end   

      def edit
          #@article=Article.find(params[:id])
      end


      def create
          #render plain: params[:article]
          #@article= Article.new(params.require(:article).permit(:title, :description))
          @article= Article.new(article_params)
          @article.user = current_user
          #render plain=article
        
        if   @article.save
          #redirect_to article_path(@article)
          flash[:notice]="Article was created successfully"
          redirect_to @article
        else 
          render 'new',status: :unprocessable_entity
        end   
      end   

      def update
        #@article =Article.find(params[:id])
        #if  @article.update(params.require(:article).permit(:title, :description))
        if  @article.update(article_params)
          flash[:notice]="Article was updated successfully."
          redirect_to @article
        else
          render 'edit',status: :unprocessable_entity
        end   
      end

      def destroy
        #@article=Article.find(params[:id])
        @article.destroy
        flash[:notice]="Article was deleted successfully"
        redirect_to articles_path
      end   

      private 

      def set_article
        @article=Article.find(params[:id])
      end  

      def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
      end
 
      def require_same_user
          if current_user != @article.user && !current_user.admin?
             flash[:alert] = "you can only edit or delete your own article"
             redirect_to @article
          end  
      end   

  
end    

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">    
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body-tertiary rounded">
          
          <div class="card-header fst-italic">
              <%if article.user%>
                by <%= link_to article.user.username,user_path(article.user)  %>
              <%end%>
              <% if article.categories.any? %>
            <div class= "mt-3"> 
               <%= render article.categories %>
            </div>
            <% end %>  
          </div>

          <div class="card-body">
            <h5 class="card-title">
              <%= link_to article.title, article_path(article), class: "text-success" %>
            </h5>
            <p class="card-text">
              <%= truncate(article.description, length: 100) %>
            </p>

            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? && (article.user == current_user || current_user.admin?)%>
                  <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                  <%= link_to 'Delete', article_path(article), method: :delete, 
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, 
                        class: "btn btn-outline-danger" %>
                <% end %>         
          </div>

          <div class="card-footer text-body-secondary">
            <small>
              Created <%= time_ago_in_words(article.created_at) %> ago, 
              Edited <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

<!--
Commented old table code before using cards:

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td>
          <%= link_to 'Delete', article_path(article), method: :delete, 
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>
-->

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors',obj: @article %>

      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>

        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
             {prompt: "Make your selection from the list below (can be empty)"},{multiple: true,size: 4, class: "custom-select form-control shadow rounded"} ) %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <div class="col text-center">
            <%= f.submit @article.new_record? ? "Create Article" : "Update Article", class: "btn btn-outline-light btn-lg" %>
          </div>
        </div>

      <% end %>

      <div class="mb-3 text-center">
        <%= link_to '[Cancel edit and return to articles listing]', articles_path, class: "text-info" %>
      </div>

    </div>
  </div>

</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
</div>

<%= render'article'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
  <h1 class="text-center mt-4"><%= @article.title %></h1>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body-tertiary rounded">
          
          <div class="card-header fst-italic">
            by <%= @article.user.username if @article.user%>
            <%= link_to gravatar_for(@article.user,size: 120),user_path(@article.user)%>
            <% if @article.categories.any? %>
            <div class= "mt-3"> 
               <%= render @article.categories %>
            </div>
            <% end %>  
          </div>

          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
           <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(@article),
                    method: :delete,
                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                    class: "btn btn-outline-danger" %>
           <% end %>       
          </div>

          <div class="card-footer text-body-secondary">
            <small>
              Created <%= time_ago_in_words(@article.created_at) %> ago,
              Edited <%= time_ago_in_words(@article.updated_at) %> ago
            </small>
          </div>

        </div>
      </div>
    </div>
  </div>






<!--
<div id="page-content">

<h2 class="text-center mt-4"><%= @article.title%><h2>


<div class="container">

<div class="row justify-content-md-center">    
 <div class="col-8 mt-4">
 <div class="card text-center shadow  mb-5 bg-body-tertiary rounded">
  <div class="card-header fst-italic">
    by Aadinath Chaudhari
  </div>
  <div class="card-body">
    
    <p class="card-text"><%= simple_format(@article.description) %></p>
     <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
     <%=link_to 'Delete',article_path(@article), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
     class:"btn btn-outline-danger" %>
    
  </div>
  <div class="card-footer text-body-secondary">
    <small>Created <%= time_ago_in_words(@article.created_at)%> ago,Edited <%=time_ago_in_words(@article.updated_at) %> ago</small>
  </div>
  </div>
 </div> 
</div>


</div> 

</div>



<h1>Showing Article details</h1>
 <p>
    <strong> Title: </strong> <%= @article.title%>
 </p>
 <p>
    <strong> Description: </strong><%= @article.description %>
 </p>

 <p>
   <%= link_to 'Edit', edit_article_path() %>
 </p>
 <p>
   <%=link_to 'Delete',article_path(), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
 </p>

 <p>
    <%= link_to 'Return to articles listing',articles_path(@article)%>
 </p>
 -->