config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :articles 
  root "pages#home"
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories,except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Aadinath Chaudhari</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name,msg| %>
    <% if name == "notice"%>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%else%>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%end%>
<%end%> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'ALPHA BLOG',root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View Articles',articles_path,class:"dropdown-item"%></li>
            <% if  logged_in? %>
            <li><%= link_to 'Create new article',new_article_path,class:"dropdown-item"%></li>
            <% end %>
            
          </ul>
        </li>
       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View categories',categories_path,class:"dropdown-item"%></li>
            <% if  logged_in? && current_user.admin? %>
            <li><%= link_to 'Create new category',new_category_path,class:"dropdown-item"%></li>
            <% end %>
            
          </ul>
        </li>

        <% if logged_in?%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               <%= "(Admin)" if current_user.admin? %> profile [<%= current_user.username%>]
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'View your profile',user_path(current_user),class:"dropdown-item"%></li>
                <li><%= link_to 'Edit your profile',edit_user_path(current_user),class:"dropdown-item"%></li>
                <li><%= link_to 'Delete profile',user_path(current_user),class:"dropdown-item text-danger", method: :delete,data: {turbo_method: :delete,turbo_confirm: "Are you sure?"}%></li>
              </ul>
            </li>
            <li class="nav-item">           
              <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link", data: { turbo_method: :delete } %>
            </li>
         <% else %> 
             <li class="nav-item">
              <%= link_to 'Log in', login_path, class: "nav-link"%>
             </li>
             <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class: "nav-link"%>
             </li>
        <%end%>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRails7App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    
   <%= render 'layouts/navigation'%>
   <div id=page-content>
   <%= render 'layouts/messages'%>

    <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>